version: "3.6"

services:
  postgres:
    restart: always
    image: postgres:10
    hostname: postgres
    container_name: postgres-1
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - default
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: downloader_db
    shm_size: 512mb
